name = "alist"
main = "src/index.ts"
compatibility_date = "2024-12-13"
minify = true
upload_source_maps = true
workers_dev = false
preview_urls = false

[observability]
enabled = true

[assets]
directory = "./dist/"

[[routes]]
pattern = "alist.chaimi.cc/*"
zone_name = "chaimi.cc"

[build]
command = "pnpm build"
